steps:
  # build the container image
- name: "gcr.io/cloud-builders/docker"
  args: ["build", "-t", "gcr.io/jasons-project-272919/quickstart-docker:v0", "."]
  # push container image
- name: "gcr.io/cloud-builders/docker"
  args: ["push", "gcr.io/jasons-project-272919/quickstart-docker:v0"]
  # deploy container image to GKE
- name: "gcr.io/cloud-builders/gke-deploy"
  args:
  - run
  - --filename=app.yaml
  - --image=gcr.io/jasons-project-272919/quickstart-docker:v0
  - --location=us-central1
  - --cluster=autopilot-cluster-1
